### ISSUE TITLE
can't fix error code 31-4302

### ISSUE THREAD

**Issue by dragon-boater** [yaagl/yet-another-anime-game-launcher#294]
**Describe the bug**
Was following the Andrew Tsai guide but when I enable the turn off AC patch I still get error  code 31-4302

![image](https://github.com/yaagl/yet-another-anime-game-launcher/assets/165424642/d1973b40-71e3-44ae-8a72-c010ce5a2bf8)
![image](https://github.com/yaagl/yet-another-anime-game-launcher/assets/165424642/348854aa-d7c9-401b-8d88-0d44f71ace20)

**System Information (please complete the following information):**
 - macOS: 14.4.1 Sonoma
 - Device: MacbookPro 16inch 2019
 - CPU: Apple M1
 - RAM: 16G

**Comment by Intro1997** [comment]
Same problem!

**Comment by Zqanx** [comment]
1. Check file integrity
2. Make sure game files aren't installed somewhere accessible by icloud (e.g. photos etc.)

**Comment by Intro1997** [comment]
> 1. Check file integrity
> 2. Make sure game files aren't installed somewhere accessible by icloud (e.g. photos etc.)

Sorry for replying so late.
I have tried your solution, but I still get the error code. And I have also tried following solutions:
1. Change my `Wine Distribution` from `crossover` to `gl-wine-1.2/1.0`. In this case I cannot open game and get error message:
```
2884436.800:0140:err:module:import_dll Library WDFLDR.SYS (which is needed by L"C:\\windows\\system32\\HoYoKProtect.sys") not found
2884436.801:0140:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\HoYoProtect": c0000142
0108: thread_get_state failed on Apple Silicon - faking zero debug registers
010c: thread_get_state failed on Apple Silicon - faking zero debug registers
0118: thread_get_state failed on Apple Silicon - faking zero debug registers
```
2. check/uncheck `Turn off the AC patch`
3. reinstall Yaagl

But I still get the error code. Is there anything else I haven't tried?

**Comment by Zqanx** [comment]
You might want to reinstall everything at this point. Or even factory reset mac os if problem still persists, up to you. Make sure to back up important files in the latter case.

**Comment by Intro1997** [comment]
> You might want to reinstall everything at this point. Or even factory reset mac os if problem still persists, up to you. Make sure to back up important files in the latter case.

Thanks for the reply. 

After turning on the "Turn off AC patch" option just now (under crossover), I was able to enter successfully. Before today, it was true that no matter whether this option was turned off or on, an error code would be displayed. Yesterday morning I re-downloaded the game, and after opening it it still displayed an error code (probably because the "Turn off AC patch" option was not turned on). After that, I didn't use any device to log into Genshin Impact for a day until I opened the launcher just now.

And I don't think factory reset Mac OS would help, the game should be running on a virtual machine, which should be an isolated environment.
