### ISSUE TITLE
Kernel Panic twice within 1 month of using YAAGL Release 0.1.10 - Genshin Impact 4.6

### ISSUE THREAD

**Issue by rotiayam** [yaagl/yet-another-anime-game-launcher#318]
Kernel Panic twice within 1 month. One was during world map run another one was during 12-3 Abyss run.

**Screenshots**
none.

**System Information (please complete the following information):**
 - macOS: 14.4.1 Sonoma
 - Device: MacbookPro 14inch 2023
 - CPU: M3 Pro
 - Dedicated GPU (if any): 
 - RAM: 18G

**Additional context**
followed Andrew Tsai's method on how to install + settings of yaagl on youtube. Any tips is welcomed.

<img width="480" alt="Screenshot 2024-05-01 at 3 24 25 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/168618494/edbe4fc2-891a-428b-b282-2327988ea64c">
<img width="441" alt="Screenshot 2024-05-01 at 3 24 34 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/168618494/808cc1a7-6f3c-4c74-a627-06faec7c49c8">
<img width="492" alt="Screenshot 2024-05-01 at 3 24 42 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/168618494/dfc90e33-86a8-416e-a1fc-ad5fb3a29165">

**Comment by Sipperz** [comment]
While playing, Make sure to not have heavy tasks running alongside, Mac will push the inactive apps memory to swap and all.

**Comment by ScathachSkadi** [comment]
The only time that I got a kernel panic was when I was using a dev beta which had a lot of logging stuff running in the background which made it heavy for the game. This behavior disappeared on RC(because the background process was removed) I would also like to advise to not to play the game with a lot of things in the background because it's running with 2 translation layers and it is not even native.

Moreover, this Andrew Tsai guy is not even affiliated with us and we did not tell him to make a video about us AND we did NOT watch his video. So, please, do not assume that we would know what you did because his video said so. The video is old already because GI got updated and it has changed a lot of behaviors.

For now, uncheck the AC patch box, lower some settings, disable subsurface scattering and dynamic character resolution if you haven't already.

**Comment by rotiayam** [comment]
> The only time that I got a kernel panic was when I was using a dev beta which had a lot of logging stuff running in the background which made it heavy for the game. This behavior disappeared on RC(because the background process was removed) I would also like to advise not to play the game with a lot of things in the background because it's running with 2 translation layers and it is not even native.
> 
> Moreover, this Andrew Tsai guy is not even affiliated with us and we did not tell him to make a video about us AND we did NOT watch his video. So, please, do not assume that we would know what you did because his video said so. The video is old already because GI got updated and it has changed a lot of behaviors.
> 
> For now, uncheck the AC patch box, lower some settings, disable subsurface scattering and dynamic character resolution if you haven't already.

Thank you for the reply. I'll do as advised.
