### ISSUE TITLE
Decompressing files too long

### ISSUE THREAD

**Issue by XaviPlayz** [yaagl/yet-another-anime-game-launcher#458]
**Describe the bug**
The decompressing files on my yaagl is too long

**Screenshots**
![Screenshot 2024-09-27 at 6 49 49 PM](https://github.com/user-attachments/assets/64cf87da-57c2-4cdd-877c-290f7055baab)

**System Information (please complete the following information):**
 - macOS: Sequoia 15.0
 - Device: Mac Mini
 - CPU: Apple M1
 - Dedicated GPU (if any): N/A
 - RAM: 8G

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by XaviPlayz** [comment]
how do you have the settings icon near it? i dont have it when installing

**Comment by xk369** [comment]
> how do you have the settings icon near it? i dont have it when installing


idk, did you try uninstall installer and download it one more time? (i deleted it via appcleaner)

you can also check your storage as follows, and if it really works, then it will look like this(c++ archive doesn't apple to game), but I closed the installer and updated it to the latest version and tried to install the game again, but it stopped (or not, because last time the download "stopped" with the same amount of memory) Maybe we should really just wait.
<img width="947" alt="Снимок экрана 2024-09-28 в 9 18 38 AM" src="https://github.com/user-attachments/assets/a4f9e3ad-5256-471f-a9ab-4a04e140a7a9">

**Comment by SipperzZz** [comment]
Only reason I can think of why its taking long, either wine bugged OR it doesn't have the required permissions OR not enough space for the game to decompress.

**Comment by XaviPlayz** [comment]
it stopped

**Comment by XaviPlayz** [comment]
i just had to change my harddrive to apfs
