### ISSUE TITLE
unable to download honkai starrail

### ISSUE THREAD

**Issue by sjaknssns** [yaagl/yet-another-anime-game-launcher#493]
**Describe the bug**
unable to download game files from yaagl hsr
**Screenshots**
<img width="1512" alt="Screenshot 2024-11-29 at 9 09 48 pm" src="https://github.com/user-attachments/assets/e9653505-54fc-4af8-b110-40896ee55110">

**System Information (please complete the following information):**
 - macOS: [15.1 sequoia]
 - Device: [ MacbookPro 14inch 2024 ]
 - CPU: [Apple M4 pro ]
 - Dedicated GPU (if any): [n/a ]
 - RAM: [ 24G ]
 - Wine Distribution: [n/a: unable to download files to reach that page]

**Additional context**
this was given: Error: Assertation failed (gameSegmentZips.length > 1)! please file an issue.
GI worked without issue, it's just hsr not working. This is unrelated, but where would be a good place to download game files locally? (as I can't download into downloads, desktops and documents, I download into icloud drive). I have 1.1t left on Icloud drive so storage definitely isn't the issue. 

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by totallynotnochi** [comment]
It seems that YAAGL on HSR w/ macs dont have .7z support

https://github.com/yaagl/yet-another-anime-game-launcher/issues/441

You need to download the files manually for 2.7 (or the latest version), some guy on reddit has DLs
https://www.reddit.com/user/RhiskOMG/comments/1h4suic/direct_download_links_for_honkai_star_rail_27/

I would recommend using Jdownloader2 to download the files as it automatically unzips them for you, instead of needing to go thru the console version of 7zip.

**Comment by Sipperz** [comment]
Just released Patch with New HSR version, please update and see if problem is resolved.

**Comment by ScathachSkadi** [comment]
Checked myself and the problem is solved.
